apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-environment-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NT548-DevOps-Group2/infrastructures.git
    targetRevision: HEAD
    path: test
    directory:
      recurse: true

  destination:
  # Change this to K8S endpoint
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true