name: Terraform Provisioning

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to create'
        options:
          - test
          - production
          - all


jobs:
  terraform-apply:
    name: Terraform Setup and Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/${{ github.event.inputs.environment }}
    permissions:
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.4"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform plan -var="access_key=${{ secrets.AWS_ACCESS_KEY }}" -var="secret_key=${{ secrets.AWS_SECRET_KEY }}" -var="token=${{ secrets.AWS_TOKEN }}"